//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSTSDataProvider.Properties.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSTSDataProvider.Properties.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grow towards the sun, be free and easy. 的本地化字符串。
        /// </summary>
        public static string AboutSlogan {
            get {
                return ResourceManager.GetString("AboutSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access Mode 的本地化字符串。
        /// </summary>
        public static string AccessMode {
            get {
                return ResourceManager.GetString("AccessMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Center 的本地化字符串。
        /// </summary>
        public static string AlignCenter {
            get {
                return ResourceManager.GetString("AlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Justify 的本地化字符串。
        /// </summary>
        public static string AlignJustify {
            get {
                return ResourceManager.GetString("AlignJustify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Left 的本地化字符串。
        /// </summary>
        public static string AlignLeft {
            get {
                return ResourceManager.GetString("AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Right 的本地化字符串。
        /// </summary>
        public static string AlignRight {
            get {
                return ResourceManager.GetString("AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background Color 的本地化字符串。
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bold 的本地化字符串。
        /// </summary>
        public static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bullets 的本地化字符串。
        /// </summary>
        public static string Bullets {
            get {
                return ResourceManager.GetString("Bullets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complete Url 的本地化字符串。
        /// </summary>
        public static string CompleteUrl {
            get {
                return ResourceManager.GetString("CompleteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cookie 的本地化字符串。
        /// </summary>
        public static string Cookie {
            get {
                return ResourceManager.GetString("Cookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CopyrightOwner 的本地化字符串。
        /// </summary>
        public static string CopyrightOwnerText {
            get {
                return ResourceManager.GetString("CopyrightOwnerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decrease Indent 的本地化字符串。
        /// </summary>
        public static string DecreaseIndent {
            get {
                return ResourceManager.GetString("DecreaseIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detail 的本地化字符串。
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Extra-Rtf 的本地化字符串。
        /// </summary>
        public static string EditExtraRtf {
            get {
                return ResourceManager.GetString("EditExtraRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string EditTab {
            get {
                return ResourceManager.GetString("EditTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit this item 的本地化字符串。
        /// </summary>
        public static string EditThisItem {
            get {
                return ResourceManager.GetString("EditThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Color 的本地化字符串。
        /// </summary>
        public static string FontColor {
            get {
                return ResourceManager.GetString("FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Data 的本地化字符串。
        /// </summary>
        public static string GetData {
            get {
                return ResourceManager.GetString("GetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grow Font 的本地化字符串。
        /// </summary>
        public static string GrowFont {
            get {
                return ResourceManager.GetString("GrowFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Increase Indent 的本地化字符串。
        /// </summary>
        public static string IncreaseIndent {
            get {
                return ResourceManager.GetString("IncreaseIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Italic 的本地化字符串。
        /// </summary>
        public static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License: 的本地化字符串。
        /// </summary>
        public static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VSTS Data Provider 的本地化字符串。
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu 的本地化字符串。
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Numbering 的本地化字符串。
        /// </summary>
        public static string Numbering {
            get {
                return ResourceManager.GetString("Numbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OKText {
            get {
                return ResourceManager.GetString("OKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open File 的本地化字符串。
        /// </summary>
        public static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OTE 的本地化字符串。
        /// </summary>
        public static string OTE {
            get {
                return ResourceManager.GetString("OTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save File 的本地化字符串。
        /// </summary>
        public static string SaveFileDialogTitle {
            get {
                return ResourceManager.GetString("SaveFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save File Failed 的本地化字符串。
        /// </summary>
        public static string SaveFileFailed {
            get {
                return ResourceManager.GetString("SaveFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save File Successfully 的本地化字符串。
        /// </summary>
        public static string SaveFileSuccessfully {
            get {
                return ResourceManager.GetString("SaveFileSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show 的本地化字符串。
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shrink Font 的本地化字符串。
        /// </summary>
        public static string ShrinkFont {
            get {
                return ResourceManager.GetString("ShrinkFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Special thanks: 的本地化字符串。
        /// </summary>
        public static string SpecialThanksText {
            get {
                return ResourceManager.GetString("SpecialThanksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Plan 的本地化字符串。
        /// </summary>
        public static string TestPlan {
            get {
                return ResourceManager.GetString("TestPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Steps 的本地化字符串。
        /// </summary>
        public static string TestStepsWindow {
            get {
                return ResourceManager.GetString("TestStepsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TestSuite 的本地化字符串。
        /// </summary>
        public static string TestSuite {
            get {
                return ResourceManager.GetString("TestSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token 的本地化字符串。
        /// </summary>
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Underline 的本地化字符串。
        /// </summary>
        public static string Underline {
            get {
                return ResourceManager.GetString("Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This software uses open source libraries: 的本地化字符串。
        /// </summary>
        public static string UsedLibraries {
            get {
                return ResourceManager.GetString("UsedLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This software uses the following third-party components: 的本地化字符串。
        /// </summary>
        public static string UsedThirdPartCompentsText {
            get {
                return ResourceManager.GetString("UsedThirdPartCompentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic 的本地化字符串。
        /// </summary>
        public static string VSTSTab {
            get {
                return ResourceManager.GetString("VSTSTab", resourceCulture);
            }
        }
    }
}
